### ISSUE TITLE
Unable to run train_vae.py

### ISSUE THREAD

**Issue by kessler-frost** [dylandjian/retro-contest-sonic#3]
Even after generating the dataset you mentioned here #2 , I am getting the following error when trying to run `python train_vae.py`,
`[TRAIN] Fetching: 25 new run from the db
[TRAIN] Last id: 0, added runs: 4 added frames: 10031
[TRAIN] current iteration: 10, averaged loss: 32442.459
Traceback (most recent call last):
  File "train_vae.py", line 140, in <module>
    main()
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "train_vae.py", line 136, in main
    train_vae(str(current_time))
  File "train_vae.py", line 102, in train_vae
    traverse_latent_space(vae, frames[0], frames[-1], total_ite)
  File "/home/paperspace/dev/retro-contest-sonic/lib/visu.py", line 24, in traverse_latent_space
    save_image(res, 'results/vae/sample_traverse_{}.png'.format(total_ite))
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/torchvision/utils.py", line 104, in save_image
    im.save(filename)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 1932, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'results/vae/sample_traverse_20.png'`
also I had to manually hardcode the timestamp in train_vae.py variable `current_time` as it was already extracting current time (and I had generated the mongodb dataset `retro_contest` earlier).

**Comment by dylandjian** [comment]
Hello !

2 things :
- you can specify the timestamp using  `python train_vae.py --folder=YOUR_TIMESTAMP`
so it chooses this timestamp instead of generating one.
- the error is probably because the folders `results/vae` don't exist at the source of the repository (which is where you are starting the python script). I could have probably pushed an empty one with a .gitkeep in it, my mistake. I believe that the error should be fixed by creating a folder results with a folder vae inside it !

**Comment by kessler-frost** [comment]
Thanks, resolved by making the directory inside the root of repo (where train_vae.py resides). Earlier I tried creating the repository in the `lib` folder, where `visu.py` is, as I thought it was supposed to be created there. Guess I didn't realise those were the functions that were being called in `train_vae.py` from `visu.py`.
